name: distal-train

resources:
  cloud: ssh
  accelerators: RTX4090:2
  cpus: 31

envs:
  HF_TOKEN:
  WANDB_API_KEY:
  MUJOCO_GL: egl
  PYOPENGL_PLATFORM: egl
  CMAKE_POLICY_VERSION_MINIMUM: 3.5
  # MUJOCO_EGL_DEVICE_ID: 0
  # SLURM_JOB_ID: 0  # suppress tqdm
  CUDA_VISIBLE_DEVICES: 0
workdir: .

setup: |
  bash ~/sky_workdir/scripts/sky_setup.sh

run: |
  cd ~/sky_workdir
  uv run python -m distal.eval_guidance
