name: distal-train

resources:
  cloud: runpod
  accelerators: H100-SXM
  # disk_size: 128
  autostop:
    idle_minutes: 10
    down: true

envs:
  HF_TOKEN:
  WANDB_API_KEY:
  MUJOCO_GL: egl
  PYOPENGL_PLATFORM: egl
  SLURM_JOB_ID: 0  # suppress tqdm
  # SUITE: libero_spatial
  # DATASET_REPO_ID: reece-omahoney/pi05-libero-plus
workdir: .

setup: |
  bash ~/sky_workdir/scripts/sky_setup.sh

run: |
  cd ~/sky_workdir
  uv run distal/train_pi_star.py
