name: distal-train

resources:
  cloud: vast
  accelerators: H100:1
  cpus: 16+
  disk_size: 64
  autostop:
    idle_minutes: 10
    down: true

envs:
  HF_TOKEN:
  WANDB_API_KEY:
  MUJOCO_GL: egl
  PYOPENGL_PLATFORM: egl

workdir: .

setup: |
  set -e

  # Fix EGL libs
  V=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader | head -1)
  apt-get update && apt-get install -y libegl1 libgl1 libglvnd0 libopengl0
  wget -q "https://us.download.nvidia.com/tesla/${V}/NVIDIA-Linux-x86_64-${V}.run" -O /tmp/nvidia.run
  chmod +x /tmp/nvidia.run && /tmp/nvidia.run --extract-only --target /tmp/nvidia-driver
  cp /tmp/nvidia-driver/{libEGL_nvidia,libnvidia-eglcore,libnvidia-glcore,libnvidia-glsi,libnvidia-tls}.so.${V} \
    /usr/lib/x86_64-linux-gnu/
  mkdir -p /usr/share/glvnd/egl_vendor.d
  echo '{"file_format_version":"1.0.0","ICD":{"library_path":"libEGL_nvidia.so.0"}}' > /usr/share/glvnd/egl_vendor.d/10_nvidia.json
  ldconfig && rm -rf /tmp/nvidia.run /tmp/nvidia-driver

  curl https://mise.run | sh
  echo 'eval "$($HOME/.local/bin/mise activate bash)"' >> ~/.bashrc
  export PATH="$HOME/.local/bin:$PATH"
  eval "$(mise activate bash)"
  cd ~/sky_workdir
  mise trust

  uv sync

  mkdir ~/.libero
  cat <<EOF > ~/.libero/config.yaml
  assets: /root/sky_workdir/.venv/lib/python3.12/site-packages/libero/libero/./assets
  bddl_files: /root/sky_workdir/.venv/lib/python3.12/site-packages/libero/libero/./bddl_files
  benchmark_root: /root/sky_workdir/.venv/lib/python3.12/site-packages/libero/libero
  datasets: /root/sky_workdir/.venv/lib/python3.12/site-packages/libero/libero/../datasets
  init_states: /root/sky_workdir/.venv/lib/python3.12/site-packages/libero/libero/./init_files
  EOF

  cd ~/sky_workdir
  python /root/sky_workdir/.venv/lib/python3.12/site-packages/robosuite/scripts/setup_macros.py

run: |
  cd ~/sky_workdir
  uv run mise run adv-train reece-omahoney/adv-libero-base
