host: u6jz.aip2.isambard
remote_path: /home/u6jz/reece.u6jz/distal

time: 24
gpu: ""
ngpu: 1
cpus: 72
mem: 1600M
partition: workq

envs:
  - WANDB_API_KEY
  - HF_TOKEN
command: |-
  export OPENBLAS_NUM_THREADS=8
  export OMP_NUM_THREADS=8
  export MKL_NUM_THREADS=8

  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.local/bin:$PATH"

  uv sync
  uv run distal/train_value.py
