job_name: pi05-remove-pen-lid
num_workers: 8
batch_size: 32
steps: 20_000
eval_freq: 0

dataset:
  repo_id: reece-omahoney/remove-pen-lid
  use_imagenet_stats: false

wandb:
  enable: true
  disable_artifact: true
  project: distal
